baseurl = "http://blog.ntcong.it"
languageCode = "en-us"
title = "Cong Nguyen"
pygmentsuseclasses=true
pygmentsstyle="solarizeddark"
disqusShortname="ntcongit"
#theme = "redlounge"
theme = "beautifulhugo"
author = "Cong Nguyen"
googleAnalytics = "UA-76172988-1"

[params]
  sidebartitle = "CongNT"
  sidebartagline = "Thoughts on Programming and anything Computer"
  subtitle = "Thoughts on Programming and anything Computer"
  sidebarphoto = '/img/avatar.png'
  logo = '/img/avatar.png'
  categoriescss = "/css/categories.css"

[Author]
  name = "Cong Nguyen"
  email = "ntcong.it@gmail.com"
  facebook = "ntcong.it"
  github = "ntcong"
  linkedin = "in/ntcong"
  stackoverflow = "104011/fu4ny"

[[menu.main]]
  name = "Blog"
  url = "/"
[[menu.main]]
  name = "About"
  url = "/about"
[[menu.social]]
  pre = "<i class='fa fa-rss'></i>"
  url = "http://blog.ntcong.it/posts/index.xml"
  identifier = "RSS"
[[menu.social]]
  pre = "<i class='fa fa-google-plus'></i>"
  url = "https://plus.google.com/+CongNguyen"
  identifier = "Google+"
[[menu.social]]
  pre = "<i class='fa fa-facebook'></i>"
  url = "https://facebook.com/ntcong.it"
  identifier = "Facebook"
[[menu.social]]
  pre = "<i class='fa fa-github'></i>"
  url = "http://github.com/ntcong"
  identifier = "GitHub"
